### PR TITLE
[ Fix ] fix custom generators not working with Gradle 4.9+

### LINKED ISSUE #82: Current version not working with Gradle 4.9+
I have tried the latest version of the plugin (manually build SNAPSHOT) and it does not work with Gradle 4.9. 

I'm using custom generators in my project and for Gradle 4.9 I don't see tasks for my custom generators.

I think it is due to #72 because for Gradle 4.9 the task registration is not executed within `project.afterEvaluate` block hence the extension is no yet configured (the generators will be always default).

### PR DESCRIPTION
**Pull request by gentrio**
Closes #82

### CODE REVIEW

**Comment by gentrio** [comment]
> Hmmm. Why do we need to wrap it with `afterEvaluate`?
if not wrap it with `afterEvaluate `, there is not custom generator task.....

**Comment by vanniktech** [comment]
Is your project open source so I could have a look?

**Comment by gentrio** [comment]
yeah you can see it https://github.com/gentrio/gradle-dependency-graph-demo

**Comment by gentrio** [comment]
How's it going ?

**Comment by vanniktech** [comment]
Haven't had time. Quite busy at the moment.

**Comment by vanniktech** [comment]
Why do you copy paste the sources? It's hard to know what's going on in that project. Can't you use the artifact?

**Pull request closed without merging**
