### PR TITLE
Add MavenCentral badge.

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by johnjohndoe** [comment]
@vanniktech The `latestVersion` variable can be defined by the user - a common pattern is to maintain all version strings in the root level `build.gradle` file. Here it is meant as a placeholder to remind users to pick the desired version.

If you publish the SNAPSHOT version on MavenCentral you could add another badge and maybe change above variable name from `latestVersion` to `latestReleaseVersion`. Than you can use `latestSnapshotVersion` for the SNAPSHOT code snippet.

**Comment by vanniktech** [comment]
We could do the badge but I don't mind maintaining the latest version. I do it in all my repos and changing it in every repo is quite a lot of work.

**Comment by johnjohndoe** [comment]
It is of course totally up to you to decide if you want to maintain the version string in the `README.md`. In my experience it is just another location where one forgets to update when a new release is shipped. Feel free to decide on you own.

**Comment by vanniktech** [comment]
If you remove the last version change I'm happy to merge.

**Pull request merged**
