### PR TITLE
Change of fill cover fails integration test.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
@SimonMarquis do you have any idea why this simple color change yields an entirely different graph? Also reported over [here](https://github.com/nidi3/graphviz-java/issues/234)

**Comment by SimonMarquis** [comment]
Interesting, I'll take a look at it.

**Comment by SimonMarquis** [comment]
I guess that somewhere we forgot to re-use the mutable graph.

**Comment by SimonMarquis** [comment]
Found it, we are creating duplicated nodes. And unfortunately changing an attribute changed the default ordering, and finally the resulting graph. I'm implementing a fix for that.

**Pull request closed without merging**
