### PR TITLE
A little hint added

### PR DESCRIPTION
**Pull request by AMK9978**
I got stuck because of not knowing above helps.

### CODE REVIEW

**Comment by AMK9978** [comment]
If you check README.md , you will find out one picture has been added for more hint and two lines, and the picture added to repo which has "Capture2.JPG" name, in addition you can change the link of image in Readme.md from my account to your account if accept it.

**Comment by AMK9978** [comment]
Please adding Capture2.JPG in your files and change the src link in README.md in this way from:
https://github.com/AMK9978/gradle-dependency-graph-generator-plugin/blob/master/Capture2.JPG?raw=true.
to:
https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/blob/master/Capture2.JPG?raw=true.
I didn't do that for viewing that in my branch.
It's about executing gradle files , which was not a clear mention in your README.md

**Comment by vanniktech** [comment]
> By default this plugin will generate a generateDependencyGraph task that can be used to generate a dependency graph that could look like this. 

Is pretty clear to me

**Comment by AMK9978** [comment]
I think mentioning to gradle and building that will be better.
In the first time I added the dependencies of repo and then I build project (Not gradle) and didn't see anything related to this repo in my project folders.

**Comment by vanniktech** [comment]
Closing since the instructions are in the README.

**Pull request closed without merging**
