### PR TITLE
Generator: Allow custom output formats.

### LINKED ISSUE #50: [Feature request] Can we export the dependency graph to svg ?
I am not falimar with `Graphviz`, is this possible ?

### PR DESCRIPTION
**Pull request by vanniktech**
Fixes #50

### CODE REVIEW

**Comment by gengjiawen** [comment]
Still not clear to me how to config svg output ? Mind add instruction to `README.md`.

**Comment by gengjiawen** [comment]
@vanniktech Hey, when will be next release available ? I am look forward to try the svg output 😃

**Comment by vanniktech** [comment]
Yes sorry. I'm trying to do that this weekend.

**Comment by vanniktech** [comment]
@gengjiawen just pushed it out. Sorry it took a bit longer.

**Pull request merged**
