### PR TITLE
Update graphviz-java to 0.18.1

### LINKED ISSUE #144: Execution failed "TypeError: Module.print is not a function" for a mono repo
```
> Task :generateDependencyGraph
Warning: Nashorn engine is planned to be removed from a future JDK release

> Task :generateDependencyGraph FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDependencyGraph'.
> TypeError: Module.print is not a function
```

It doesn't matter if I use the 0.8.0-SNAPSHOT or 0.7.0.
Any idea on how to fix that?

### PR DESCRIPTION
**Pull request by SimonMarquis**
Closes #145 and should fix #144 as well.

### CODE REVIEW

**Comment by vanniktech** [comment]
Probably just like in the other PRs, tests are failing

**Comment by SimonMarquis** [comment]
I'm on it. The default graphviz .dot output has changed.
There might be other errors though.

**Comment by SimonMarquis** [comment]
@vanniktech I think I'll have to way for #150.
[DependencyGraphGeneratorPluginTest.integrationTestGradle50](https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/runs/6739136811?check_suite_focus=true#step:5:112) fails on CI and locally.

**Comment by vanniktech** [comment]
@SimonMarquis can you please rebase / merge with master?

**Review by vanniktech — APPROVED** [review]
Dope thanks!

**Comment by SimonMarquis** [comment]
It seems like it is stuck on a test. On my local machine the jvm crashes quite fast with an OOM.

**Comment by vanniktech** [comment]
Interesting, I have:

```
com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPluginTest > integrationTestGradle742 FAILED
    org.junit.ComparisonFailure: expected:<digraph "G" {
    [node ["fontname"="Times New Roman"]
    "junit9628386895718580820" ["shape"="rectangle","label"="junit9628386895718580820"]
    "orgjetbrainskotlinkotlinstdlib" ["shape"="rectangle","label"="kotlin-stdlib"]
    "orgjetbrainsannotations" ["shape"="rectangle","label"="jetbrains-annotations"]
    "ioreactivexrxjava2rxjava" ["shape"="rectangle","label"="rxjava"]
    "orgreactivestreamsreactivestreams" ["shape"="rectangle","label"="reactive-streams"]
    {]
    graph ["rank"="same...> but was:<digraph "G" {
    [edge ["dir"="forward"]
    node ["fontname"="Times New Roman"]
    "junit9628386895718580820" ["label"="junit9628386895718580820","shape"="rectangle"]
    "orgjetbrainskotlinkotlinstdlib" ["label"="kotlin-stdlib","shape"="rectangle"]
    "orgjetbrainsannotations" ["label"="jetbrains-annotations","shape"="rectangle"]
    "ioreactivexrxjava2rxjava" ["label"="rxjava","shape"="rectangle"]
    "orgreactivestreamsreactivestreams" ["label"="reactive-streams","shape"="rectangle"]
    {
    edge ["dir"="none"]]
    graph ["rank"="same...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPluginTest.integrationTest(DependencyGraphGeneratorPluginTest.kt:96)
        at com.vanniktech.dependency.graph.generator.DependencyGraphGeneratorPluginTest.integrationTestGradle742(DependencyGraphGeneratorPluginTest.kt:55)
```

**Comment by vanniktech** [comment]
Can you try including: https://github.com/vanniktech/Emoji/blob/2691a11028bb854f2a2816ce6a50879f686c3578/gradle.properties#L28

**Comment by SimonMarquis** [comment]
I also get those kind of errors on the `integrationTestGradle742` test...

```
> Task :generateDependencyGraph FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateDependencyGraph'.
> Problem executing javascript
```

**Comment by vanniktech** [comment]
Can you run with `--stacktrace`?

**Comment by SimonMarquis** [comment]
I now have the same test failures, I'll fix them right now.

**Comment by vanniktech** [comment]
At least now it fails with: `Expiring Daemon because JVM heap space is exhausted`, can you try giving it some more RAM?

**Comment by SimonMarquis** [comment]
I'm not sure the jvm options specified in `gradle.properties` is applied to the test scenario. I tried to add them manually on the GradleRunner arguments.

**Comment by vanniktech** [comment]
Can you try on the GradleRunner `.withDebug(true)`. IIRC that worked in some scenario on some project somewhere some time ago

**Comment by SimonMarquis** [comment]
There it is : https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/runs/6740007186?check_suite_focus=true#step:5:50

```
    > Task :generateDependencyGraph FAILED
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':generateDependencyGraph'.
    > Problem executing javascript
```

**Comment by SimonMarquis** [comment]
Removing the custom font fixed the build on my machine 🤯

**Comment by vanniktech** [comment]
> Removing the custom font fixed the build on my machine 🤯

Meaning the OOM that we get on CI as well?

**Comment by SimonMarquis** [comment]
No, only the `> Problem executing javascript`.
The OOM seems to be fixed by this: https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/151/commits/9235955283fce41336e905ffda7be7ef4cafb9a0

**Comment by SimonMarquis** [comment]
🎉 

So I guess forcing the `Times New Roman` font is not that important right?
Also, should I revert https://github.com/vanniktech/gradle-dependency-graph-generator-plugin/pull/151/commits/e4e72f6aba96165d1b5fde41086eda7a96397d96 or keep it?

**Comment by vanniktech** [comment]
You're a legend! 

I don't remember why I forced the font, but that basically implies it's not important.

**Comment by SimonMarquis** [comment]
Thank you for the other necessary updates 🙏
The default value seems to be `Times-Roman`: https://graphviz.org/docs/attrs/fontname/
I would try to do a diff to see what has changed.

**Pull request merged**
